apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-gateway
  labels: 
    app: api-gateway
spec:
  replicas: 1
  template:
    metadata: 
      labels: 
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: gcr.io/project-tilas/api-gateway:${TAG}
        command:
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: api-gateway-config
            mountPath: /etc/api-gateway/
            readOnly: true
        env:
        - name: API_GATEWAY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: API_GATEWAY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumes:
        - name: api-gateway-config
          configMap: { name: api-gateway-config }
---
kind: Service
apiVersion: v1
metadata:
  name: api-gateway
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080